Make filter_configure() available to interfaces.inc
interfaces.inc does not know about filter_configure()
Fatal error: Call to undefined function filter_configure() in /etc/inc/interfaces.inc on line 3350 
after release then renew of a DHCP interface from the Status:Interface GUI.
Forum topic http://forum.pfsense.org/index.php/topic,52046.0.html