System / User Manager / Groups / Edit / Add Privileges
Not certain that the list needs to be sorted here.  Looks like it is already in order.  If it does then a valid callback function will need to be accessible.

Error: Non-space characters found without seeing a doctype first. Expected e.g. <!DOCTYPE html>.

Warning: uasort() expects parameter 2 to be a valid callback, function 'cpusercmp' not found or invalid function name in /usr/local/www/system_groupmanager_addprivs.php on line 91

Error: Element head is missing a required instance of child element title.

Warning: uasort() expects parameter 2 to be a valid callback, function 'cpusercmp' not found or invalid function name in /usr/local/www/system_groupmanager_addprivs.php on line 91

Error: Stray doctype.

Error: Stray start tag html.