require filter.inc so filter_configure is defined
The "renew" button on a DHCP connection ends up calling function interface_dhcpv6_configure() in interfaces.inc, which in turn calls filter_configure() (in filter.inc) but gives the error:
Fatal error: Call to undefined function filter_configure() in /etc/inc/interfaces.inc on line 3350
See forum post: http://forum.pfsense.org/index.php/topic,52046.0.html