Fix config_del_path() if the node doesn't exist
If the node we're trying to delete with config_del_path() doesn't exist
array_del_path() will fail as follows:

Fatal error: Uncaught TypeError: Cannot access offset of type string on string in /etc/inc/util.inc:3459
Stack trace:
  thrown in /etc/inc/util.inc on line 3459
PHP ERROR: Type: 1, File: /etc/inc/util.inc, Line: 3459, Message: Uncaught TypeError: Cannot access offset of type string on string in /etc/inc/util.inc:3459
Stack trace:
  thrown

Check to make sure the element we found is an array and contains the key
we're trying to delete before we try to delete it.